version: '3.8'
services:
  # 1. MySQL (RDB)
  mysql:
    image: mysql:8.0
    container_name: template-mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: ["mysql_data:/var/lib/mysql"]

  # 2. DynamoDB Local (NoSQL)
  ddb-local:
    image: amazon/dynamodb-local:latest
    container_name: template-ddb
    user: root  # 권한 문제를 해결하기 위해 추가
    ports: ["8001:8000"]
    # 상대 경로(./data) 대신 컨테이너 내부의 절대 경로(/home/dynamodblocal/data)를 사용합니다.
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes: ["ddb_data:/home/dynamodblocal/data"]

  # 3. MinIO (S3 호환 저장소)
  s3:
    image: minio/minio
    container_name: template-s3
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes: ["s3_data:/data"]

volumes:
  mysql_data:
  ddb_data:
  s3_data: